# fly.toml app configuration file generated for shopper on 2023-11-28T14:29:32-08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shopper"
primary_region = "iad"

[build]

[env]
  PORT = "8081"
  SCOPES = "write_products"
  SHOPIFY_API_KEY = "8a246cd7392f3a0d1afc55fa2da1df8a"
  SHOPIFY_APP_URL = "https://shopper.fly.dev"

[http_service]
  internal_port = 8081
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024
