# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "shopper"
client_id = "8a246cd7392f3a0d1afc55fa2da1df8a"
application_url = "https://petition-pens-developmental-trust.trycloudflare.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://petition-pens-developmental-trust.trycloudflare.com/auth/callback",
  "https://petition-pens-developmental-trust.trycloudflare.com/auth/shopify/callback",
  "https://petition-pens-developmental-trust.trycloudflare.com/api/auth/callback",
  "https://petition-pens-developmental-trust.trycloudflare.com/.shopify/graphiql/auth/callback"
]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false

[build]
automatically_update_urls_on_dev = true
dev_store_url = ".myshopify.com"
