# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "shopper"
client_id = "8a246cd7392f3a0d1afc55fa2da1df8a"
application_url = "https://example.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2023-10"

[pos]
embedded = false
