name: 'main_cicd'

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: read

concurrency:
  group: '${{ github.workflow }} @ ${{ github.event.pull_request.head.label || github.head_ref || github.ref }}'
  cancel-in-progress: true

jobs:
  test_matrix:
    strategy:
      matrix:
        flavor: [unit,integration]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test
        run: npx vitest --coverage --run

      - name: Vitest Coverage Report
        uses: davelosert/vitest-coverage-report-action@v2.1.1
        with:
          name: 'test coverage'
          json-summary-path: './coverage/coverage-summary.json'